//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkingmesto
    {
        public string oznaka { get; set; }
        public string trenutnoStanje { get; set; }
        public int id { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public string vremeDolaska { get; set; }
        public int Orijentacija { get; set; }
    }
}
